### ISSUE TITLE
[Insight] Text files should end with a newline character - in Resources/config/services.yml, line 14

### ISSUE THREAD

**Issue by beyerz** [beyerz/OpenGraphProtocolBundle#5]
**[in Resources/config/services.yml, line 14](https://github.com/beyerz/OpenGraphProtocolBundle/blob/d4c24c3191eadd31c8460bac23ebbee20ecf2bf5/Resources/config/services.yml#L14)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
    beyerz.twig.beyerz_open_graph_protocol_extension:
        class: Beyerz\OpenGraphProtocolBundle\Twig\Extensions\OpenGraphProtocolExtension
        calls:
            - [setOpenGraph, ["@beyerz.ogp.open_graph"]]
        tags:
            - { name: twig.extension }
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/5d246498-8f3e-470e-ac98-371576c51759/analyses/1)_
